### ISSUE TITLE
Direct people to develop Higan instead of Ares?

### ISSUE THREAD

**Issue by ualaa1** [ares-emu/ares#13]
According to https://twitter.com/BahamutLagoon25/status/1346526760364511233 Near (formally known as byuu) plans to port all changes of Ares into Higan after he is done with his fan translation. This makes Ares redundant. Maybe place a link in the readme for Higan and tell people to develop there and probably archive this respiratory?

**Comment by Screwtapello** [comment]
All the contents of this repository have already been merged into higan. The reason this repository remains is so that people who want permissively-licensed emulation cores to build on have an official source to fork from, and so that people who feel strongly about permissively-licensing their contributions have a central place to contribute to. I think that's reason enough for this repository to keep existing, and to stay un-archived.

The README doesn't specifically tell people to go use higan instead, but it does say "The community-maintained higan project has incorporated the improvements from ares v115" and it does link to higan in the first paragraph, so I trust people to check out both forks for themselves and decide which one they want to contribute to.

Thanks for your suggestion, though!
